### PR TITLE
text size of pagination's prev and next buttons decreased

### LINKED ISSUE #628: Fix next and previous labels
Screenshot_20201120-140811_RDT Open Reader

Next and previous labels look distorted when compared with the English version.

### PR DESCRIPTION
**Pull request by zeeshan-vd**
Closes #628

### CODE REVIEW

**Comment by vincent-karuri** [comment]
@zeeshan-vd Do the next and prev fields' widths wrap content? I think maybe setting a fixed 14sp size may still be a problem in some devices? Would it be better to allow the fields to take up as much space as they need?

**Comment by zeeshan-vd** [comment]
> @zeeshan-vd Do the next and prev fields' widths wrap content? I think maybe setting a fixed 14sp size may still be a problem in some devices? Would it be better to allow the fields to take up as much space as they need?

In that case the middle text (page 1 of 3) might get overlapped. Another solution might be to ellipsize next and prev text?

**Comment by vincent-karuri** [comment]
> > @zeeshan-vd Do the next and prev fields' widths wrap content? I think maybe setting a fixed 14sp size may still be a problem in some devices? Would it be better to allow the fields to take up as much space as they need?
> 
> @vincent-karuri In that case the middle text (page 1 of 3) might get overlapped. Another solution might be to ellipsize next and prev text?

Ok, if it doesn't fit then this is fine.

**Comment by vincent-karuri** [comment]
The text looks a bit tiny (hard to read) though. Could we shorten the text to `1 dari 3` and keep the previous size or `Halaman 1` or  just the numbers.

**Comment by zeeshan-vd** [comment]
Yes, that can be done. I'll create the PR on [opensrp-client-core](https://github.com/OpenSRP/opensrp-client-core) repo to make the width = wrap-content.

**Comment by vincent-karuri** [comment]
> Yes, that can be done. I'll create the PR on [opensrp-client-core](https://github.com/OpenSRP/opensrp-client-core) repo to make the width = wrap-content.

@zeeshan-vd @syedowaisali90 when making this change please make it configurable in client core such that an app can decided how to generate the page labels i.e. the portion that say `1 of 3`.

**Pull request merged**
