### PR TITLE
Split supporting investigations history section

### LINKED ISSUE #474: Split supporting investigations history section
With the splitting of supporting investigations form into White Blood Cell count and X-Ray forms, the supporting investigations patient history section will need to be split into the corresponding sections.

### PR DESCRIPTION
**Pull request by syedowaisali90**
Hi, @vincent-karuri I have created a PR for review.
Close #474

### CODE REVIEW

**Comment by vincent-karuri** [comment]
Some extra work will be needed to populate the new sections with data. Take a look at the `CovidPatientHistoryActivity` for more insight.

**Comment by vincent-karuri** [comment]
I still don't think this works. Were you able to test that a new xray and wbc form submission is viewable from the patient history?

**Comment by vincent-karuri** [comment]
`FormKeyTextExtractionUtil` also needs updating.

**Comment by syedowaisali90** [comment]
> I still don't think this works. Were you able to test that a new xray and wbc form submission is viewable from the patient history?

Yes, it was not showing but after updating the `FormKeyTextExtractionUtil` it's showing.

**Review by vincent-karuri — APPROVED** [review]

**Pull request merged**
