### PR TITLE
Not allowing enter in the answer field on the new client record form

### LINKED ISSUE #907: Not allowing enter in the answer field on the new client record form
Enter is allowed in the new client record form. However, in the other forms, it is not allowed because there will be validation error messages saying “only alphabet characters allowed”. Please kindly also apply that to the answer field in the new client record.

### PR DESCRIPTION
**Pull request by yussin-hidayat**
close #907

### CODE REVIEW

**Comment by vincent-karuri** [comment]
@yussin-hidayat does enter here mean space?

**Comment by yussin-hidayat** [comment]
> @yussin-hidayat does enter here mean space?

No, newline. Its "enter" button on keyboard.

**Comment by vincent-karuri** [comment]
> > @yussin-hidayat does enter here mean space?
> 
> No, newline. Its "enter" button on keyboard.

And adding a space to the regex achieves this?

**Comment by yussin-hidayat** [comment]
> > > @yussin-hidayat does enter here mean space?
> > 
> > 
> > No, newline. Its "enter" button on keyboard.
> 
> And adding a space to the regex achieves this?

No, the point is regex that contains any chars except newline. The regex that I added is specific to name and ID.

**Comment by vincent-karuri** [comment]
Sorry, I'm still confused https://github.com/onaio/rdt-standard/issues/907#issue-827124709 is talking about enter being allowed. What is it that's happening right now which we want to remove/modify? How is it related to the regex changes in this pr?

**Comment by yussin-hidayat** [comment]
> Sorry, I'm still confused [#907 (comment)](https://github.com/onaio/rdt-standard/issues/907#issue-827124709) is talking about enter being allowed. What is it that's happening right now which we want to remove/modify? How is it related to the regex changes in this pr?

Can I disable enter without regex?

**Comment by vincent-karuri** [comment]
> > Sorry, I'm still confused [#907 (comment)](https://github.com/onaio/rdt-standard/issues/907#issue-827124709) is talking about enter being allowed. What is it that's happening right now which we want to remove/modify? How is it related to the regex changes in this pr?
> 
> Can I disable enter without regex?

Is the objective to not allow users to press enter? What other existing field exhibits the behavior you want to implement? Could you post a link to it?

**Comment by yussin-hidayat** [comment]
> > > Sorry, I'm still confused [#907 (comment)](https://github.com/onaio/rdt-standard/issues/907#issue-827124709) is talking about enter being allowed. What is it that's happening right now which we want to remove/modify? How is it related to the regex changes in this pr?
> > 
> > 
> > Can I disable enter without regex?
> 
> Is the objective to not allow users to press enter? What other existing field exhibits the behavior you want to implement? Could you post a link to it?

https://github.com/onaio/rdt-standard/blob/ca96bf0638b078fd7f35d93fae771863b79da619/rdt-open-reader/src/covidIndonesia/assets/json.form/patient-diagnostics-form-original.json#L1046

**Review by vincent-karuri — APPROVED** [review]

**Pull request merged**
