### PR TITLE
Update wbc-form_in.properties

### PR DESCRIPTION
**Pull request by mwkhan1983**
add keys for min and max error in wbc form

### CODE REVIEW

**Comment by vincent-karuri** [comment]
@mwkhan1983 There are no translations provided for those keys so this won't fix the issue.

**Comment by mwkhan1983** [comment]
I have added so ellya can provide translations against those

**Comment by vincent-karuri** [comment]
These should be added to the english version. If they already exist there, then they should show on transifex.

**Comment by vincent-karuri** [comment]
Closing as outdated

**Pull request closed without merging**
