### PR TITLE
Validate minimum allowed date

### LINKED ISSUE #449: VTM expiration date confirmation
We need to identify if a VTM is expired based on the date they enter. Currently, we allow users to enter expired VTMs and conduct their sample collection. We should in fact ask them to use a different VTM and explain that the one they used has been expired.

We could do this by creating an error under the VTM expiration date scroll bar "The VTM you have entered has expired. Use a new VTM and update the expiration date."

### PR DESCRIPTION
**Pull request by vincent-karuri**
Closes #449.

### CODE REVIEW

**Review by pld — CHANGES_REQUESTED** [review]
can you please add unit tests directly against `MaxAllowedDataValidator`

**Comment by pld** [comment]
@vincent-karuri does NativeForm support encoding constraints in form definitions?

**Comment by vincent-karuri** [comment]
> @vincent-karuri does NativeForm support encoding constraints in form definitions?

I'm not sure I understand the question.

1. There's relevance for hiding / showing items based on some expression
1. There's calculations for deriving or setting a new value based on other existing values
1. There's validators for constraining values and raising errors if the constraint is broken

**Comment by pld** [comment]
> > @vincent-karuri does NativeForm support encoding constraints in form definitions?
> 
> I'm not sure I understand the question.
> 
>     1. There's relevance for hiding / showing items based on some expression
> 
>     2. There's calculations for deriving or setting a new value based on other existing values
> 
>     3. There's validators for constraining values and raising errors if the constraint is broken

Yea that's the question, and (3) answers it as yes, isn't that what we're doing here? Is there a reason we need specific code as logic to handle these constraints instead of using NativeForm?

**Comment by vincent-karuri** [comment]
> > > @vincent-karuri does NativeForm support encoding constraints in form definitions?
> > 
> > 
> > I'm not sure I understand the question.
> > ```
> > 1. There's relevance for hiding / showing items based on some expression
> > 
> > 2. There's calculations for deriving or setting a new value based on other existing values
> > 
> > 3. There's validators for constraining values and raising errors if the constraint is broken
> > ```
> 
> Yea that's the question, and (3) answers it as yes, isn't that what we're doing here? Is there a reason we need specific code as logic to handle these constraints instead of using NativeForm?

Cool, we don't have a comprehensive list of validators - they're built to be extensible. So if there's no validator that addresses the specific constraint you want to enforce, you build one out and add it to your field for validation.

One could've opted to add this validator to native forms if it was generalizable enough (it's debatable whether it is) but I chose to add it here instead.

**Comment by pld** [comment]
> > > > @vincent-karuri does NativeForm support encoding constraints in form definitions?
> > > 
> > > 
> > > I'm not sure I understand the question.
> > > ```
> > > 1. There's relevance for hiding / showing items based on some expression
> > > 
> > > 2. There's calculations for deriving or setting a new value based on other existing values
> > > 
> > > 3. There's validators for constraining values and raising errors if the constraint is broken
> > > ```
> > 
> > 
> > Yea that's the question, and (3) answers it as yes, isn't that what we're doing here? Is there a reason we need specific code as logic to handle these constraints instead of using NativeForm?
> 
> Cool, we don't have a comprehensive list of validators - they're built to be extensible. So if there's no validator that addresses the specific constraint you want to enforce, you build one out and add it to your field for validation.
> 
> One could've opted to add this validator to native forms if it was generalizable enough (it's debatable whether it is) but I chose to add it here instead.

OK I see, I think a `DateRangeValidator` would be reasonably generalizable to move to NF, but this is not that, so sounds good.

**Review by pld — APPROVED** [review]

**Pull request merged**
