### PR TITLE
Rdt Instrumentation tests

### PR DESCRIPTION
**Pull request by Mstjamush**

### CODE REVIEW

**Comment by pld** [comment]
@Mstjamush can we merge this?

**Comment by Mstjamush** [comment]
> @Mstjamush can we merge this?

@pld No. Please don't. This is a draft PR for testing .travis.yml changes for instrumentation tests

**Comment by pld** [comment]
k won't, can you spend some to get this into a mergeable state please?

**Comment by Mstjamush** [comment]
> k won't, can you spend some to get this into a mergeable state please?

Sure

**Comment by pld** [comment]
Cool, thanks, we might have some external contributors on this project, want to have testing and static analysis looking good

**Comment by Mstjamush** [comment]
Welcome. I'll have it ready ASAP

**Pull request merged**
